//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UltimateLabs.Web.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PresentacionXProducto
    {
        public int Id { get; set; }
        public Nullable<int> IdProducto { get; set; }
        public Nullable<int> IdPresentacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string UsuarioCreacion { get; set; }
        public string FechaModificacion { get; set; }
        public string UsuarioModificacion { get; set; }
    
        public virtual Presentaciones Presentaciones { get; set; }
        public virtual Productos Productos { get; set; }
    }
}
